### ISSUE TITLE
Project Results - Comment on missing features or requirements not met [3/3]

### ISSUE THREAD

**Issue by Enari** [Enari/DVA313#164]

**Comment by caldi5** [comment]
no mention of being able to filter artifacts based on labels like in github?

**Comment by kevintroko** [comment]
I'm writing now about the "being able to filter artifacts based on labels"

**Comment by kevintroko** [comment]
Now it's ready for being reviewed

**Comment by Icepool** [comment]
I've reviewed this, left some comments.
Once their fixed it should be fine.

**Comment by caldi5** [comment]
@kevintroko get on this plsplspls

**Comment by kevintroko** [comment]
I did read the review and modify the document, If you feel it is fine you can close this issue. Same for the additional functionalities or improvements

**Comment by Icepool** [comment]
Yeah, this works. 
I've copied the new version of the text into the main document.

**Comment by Icepool** [comment]
I also copied the changes in "Possible improvements and extensions to the product" into the main document. 
From now on, if you want to edit something do it in the main document, [linked here](https://docs.google.com/document/d/1UtpavJW0-PpgZ8BCW4aWoJrIBkI0DiUZ3rG1OI1Q260/edit).

**Comment by Icepool** [comment]
@kevintroko ^
