### ISSUE TITLE
Fix Design Description "ER Diagram" [1/1]

### ISSUE THREAD

**Issue by hdzana** [Enari/DVA313#193]
- update it

**Comment by Icepool** [comment]
**Card:**
ID, SwimlaneID, ArtifactID, ProjectID, CategoryID, CreatedAt, UpdatedAt
The card doesn't have a ProjectID.

The database has the following:
id, artifact_id, category_id, swimlane_id, created_at, updated_at

**Artifact:**
The database doesn't have ProjectID's in the artifact table.

**Parent Category:**
For the ParentCategoryID, we have that connection, but there's not foreign key linking them.
But that's probably fine as we are still using them as if they have a foreign key between them.

**User:**
You didn't include the remember_token, but that's probably fine.


# Foreign keys in the code:

```php

Schema::table('cards', function ($table) {
	$table->foreign('artifact_id')->references('id')->on('artifacts')->onDelete('cascade');;
	$table->foreign('category_id')->references('id')->on('categories')->onDelete('cascade');
	$table->foreign('swimlane_id')->references('id')->on('swimlanes')->onDelete('cascade');
});

```


## The tables, after a fresh migration:
**Cards:**

| Field       | Type             | Null | Key | Default | Extra          |
| :---: | :---: | :---: | :---: | :---: | :---: |
| id          | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| artifact_id | varchar(255)     | NO   | MUL | NULL    |                |
| category_id | int(10) unsigned | YES  | MUL | NULL    |                |
| swimlane_id | int(10) unsigned | YES  | MUL | NULL    |                |
| created_at  | timestamp        | YES  |     | NULL    |                |
| updated_at  | timestamp        | YES  |     | NULL    |                |

**Swimlanes:**

| Field      | Type             | Null | Key | Default | Extra          |
| :---: | :---: | :---: | :---: | :---: | :---: |
| id         | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| name       | varchar(255)     | NO   |     | NULL    |                |
| sortnumber | int(11)          | NO   |     | NULL    |                |
| created_at | timestamp        | YES  |     | NULL    |                |
| updated_at | timestamp        | YES  |     | NULL    |                |

**Artifacts:**

| Field       | Type         | Null | Key | Default | Extra |
| :---: | :---: | :---: | :---: | :---: | :---: |
| id          | varchar(255) | NO   | PRI | NULL    |       |
| title       | varchar(255) | NO   |     | NULL    |       |
| createdDate | varchar(255) | NO   |     | NULL    |       |
| status      | varchar(255) | NO   |     | NULL    |       |
| description | longtext     | NO   |     | NULL    |       |
| assignedTo  | varchar(255) | NO   |     | NULL    |       |
| created_at  | timestamp    | YES  |     | NULL    |       |
| updated_at  | timestamp    | YES  |     | NULL    |       |

**Categories:**

| Field          | Type             | Null | Key | Default | Extra          |
| :---: | :---: | :---: | :---: | :---: | :---: |
| id             | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| name           | varchar(255)     | NO   |     | NULL    |                |
| limit          | int(11)          | NO   |     | NULL    |                |
| sortnumber     | int(11)          | NO   |     | NULL    |                |
| parentcategory | int(10) unsigned | YES  |     | NULL    |                |
| created_at     | timestamp        | YES  |     | NULL    |                |
| updated_at     | timestamp        | YES  |     | NULL    |                |

**Users:**

| Field          | Type             | Null | Key | Default | Extra          |
| :---: | :---: | :---: | :---: | :---: | :---: |
| id             | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| username       | varchar(255)     | NO   | UNI | NULL    |                |
| password       | varchar(255)     | NO   |     | NULL    |                |
| isadmin        | tinyint(1)       | NO   |     | 0       |                |
| remember_token | varchar(100)     | YES  |     | NULL    |                |
| created_at     | timestamp        | YES  |     | NULL    |                |
| updated_at     | timestamp        | YES  |     | NULL    |                |


**Projects:**

| Field          | Type         | Null | Key | Default | Extra |
| :---: | :---: | :---: | :---: | :---: | :---: |
| project_id     | varchar(255) | NO   | PRI | NULL    |       |
| createdBy      | varchar(255) | NO   |     | NULL    |       |
| title          | varchar(255) | NO   |     | NULL    |       |
| description    | longtext     | NO   |     | NULL    |       |
| artifact_fetch | tinyint(1)   | NO   |     | 0       |       |
| created_at     | timestamp    | YES  |     | NULL    |       |
| updated_at     | timestamp    | YES  |     | NULL    |       |

**Parent Categories:**

| Field      | Type             | Null | Key | Default | Extra          |
| :---: | :---: | :---: | :---: | :---: | :---: |
| id         | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| name       | varchar(255)     | NO   |     | NULL    |                |
| limit      | int(11)          | NO   |     | NULL    |                |
| created_at | timestamp        | YES  |     | NULL    |                |
| updated_at | timestamp        | YES  |     | NULL    |                |

**Comment by AmerSurkovic** [comment]
Fixed it. I hope.
